title: Jeckun's Sharing
description: Jeckun
google_analytics: 
show_downloads: true
theme: 

destination: _site

gems:
  - jekyll-mentions

collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag